version: '3.6'
################################################################################
### EXAMPLE: Use p2p build configuration to run a p2p only node
################################################################################
# services:
#     nodeos:
#         extends:
#             file: ./configs/docker/nodeos-minimal-p2p.yaml
#             service: nodeos